### ISSUE TITLE
生成报错 ValueError: Need to enable queue to use generators.

### ISSUE THREAD

**Issue by hhucchenyixiao** [v3ucn/Causallm14b_llama_webui_adult_version#1]
使用 conda 部署，点击生成后报错
```
Traceback (most recent call last):
  File "C:\software\miniconda3\envs\causallm14b\lib\site-packages\gradio\routes.py", line 534, in predict
    output = await route_utils.call_process_api(
  File "C:\software\miniconda3\envs\causallm14b\lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\software\miniconda3\envs\causallm14b\lib\site-packages\gradio\blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "C:\software\miniconda3\envs\causallm14b\lib\site-packages\gradio\blocks.py", line 1193, in call_function
    raise ValueError("Need to enable queue to use generators.")
ValueError: Need to enable queue to use generators.
```
求大佬解决一下。

**Comment by uksin-u** [comment]
我也遇到了，在app.py的最后一行的app.launch里加入参数enable_queue=True解决。

**Comment by hhucchenyixiao** [comment]
> 我也遇到了，在app.py的最后一行的app.launch里加入参数enable_queue=True解决。

感谢，现在可以生成了 ，但是好像默认是在CPU上跑，怎么设置它在显卡上跑呢？

**Comment by YuanWenHai** [comment]
> > 我也遇到了，在app.py的最后一行的app.launch里加入参数enable_queue=True解决。
> 
> 感谢，现在可以生成了 ，但是好像默认是在CPU上跑，怎么设置它在显卡上跑呢？

遇到了相同的问题，请问你最后是怎么解决的呢
