### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by chinabestcountry** [v3ucn/Causallm14b_llama_webui_adult_version#2]
启动时显示`Traceback (most recent call last):
  File "app.py", line 11, in <module>
    llm = Llama(
TypeError: __init__() got an unexpected keyword argument 'chat_format'
`
有大佬知道怎么回事吗

**Comment by chinabestcountry** [comment]
全文
`Exception ignored in: <function Llama.__del__ at 0x149c0b28d160>
Traceback (most recent call last):
  File "/usr/local/miniconda3/lib/python3.8/site-packages/llama_cpp/llama.py", line 1507, in __del__
    if self.model is not None:
AttributeError: 'Llama' object has no attribute 'model'
Traceback (most recent call last):
  File "app.py", line 11, in <module>
    llm = Llama(
TypeError: __init__() got an unexpected keyword argument 'chat_format'
`
